name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SAMPLE_FUNCTION
      id: sample_function
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: SAMPLE_FUNCTION
        setup-command: ''
        command: javac samplefunction.java && java samplefunction
        input: ''
        expected-output: ''
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAMPLE_FUNCTION_RESULTS: "${{steps.sample_function.outputs.result}}"
      with:
        runners: sample_function
